[build]
  command = "npm run build"
  publish ="dist"

[[redirects]]
  from = "/*"
  to ="/index.html"
  status = 200

# Environment variables for production (non-sensitive only)
[context.production.environment]
  NODE_ENV = "production"